[tool.poetry]
name = "qcop"
version = "0.1.0"
description = "A package for operating Quantum Chemistry programs using qcio standardized data structures."
authors = ["Colton Hicks <github@coltonhicks.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
qcio = { path = "../qcio", develop = true }


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
ruff = "^0.0.272"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
